import { Emergency } from "../../domain/entities/emergency.entity";

/**
 * Datos semilla — insertados vía "on_conflict=id, ignore-duplicates" al
 * primer read, para que el Frontend tenga datos reales que consultar desde
 * el primer momento sin depender de que alguien los haya creado antes.
 */
export const SEED_EMERGENCIES: Emergency[] = [
  new Emergency({
    id: "EMG-2024-0001",
    tipo: "SEARCH_RESCUE_MEDICAL",
    prioridad: "CRITICA",
    ciudad: "CHOCO",
    descripcion: "Edificio residencial colapsado parcialmente, se escuchan personas atrapadas en el segundo piso.",
    latitud: 5.6919,
    longitud: -76.6583,
    estado: "EN_ATENCION",
    fechaCreacion: "2026-08-20T08:12:00-05:00",
    fechaActualizacion: "2026-08-20T08:41:00-05:00",
    datosEspecificos: {
      personasAtrapadasOHeridas: 4,
      riesgoInminente: true,
      fugaDeGas: true,
      fuego: false,
      otrosRiesgos: "Estructura inestable, riesgo de colapso total.",
    },
  }),
  new Emergency({
    id: "EMG-2024-0002",
    tipo: "SHELTER_TEMPORARY_HOUSING",
    prioridad: "ALTA",
    ciudad: "PEREIRA",
    descripcion: "Familia de 6 personas sin vivienda habitable tras el sismo, requiere albergue temporal.",
    latitud: 4.8143,
    longitud: -75.6946,
    estado: "ASIGNADA",
    fechaCreacion: "2026-08-20T09:03:00-05:00",
    fechaActualizacion: "2026-08-20T09:30:00-05:00",
    datosEspecificos: {
      numeroAdultos: 2,
      numeroNinos: 3,
      numeroAdultosMayores: 1,
      requerimientosAccesibilidad: "Adulto mayor con movilidad reducida.",
      estadoHabitabilidadVivienda: "NO_HABITABLE",
    },
  }),
  new Emergency({
    id: "EMG-2024-0003",
    tipo: "BASIC_SUPPLIES_HUMANITARIAN_AID",
    prioridad: "MEDIA",
    ciudad: "CALI",
    descripcion: "Comunidad de 40 familias sin acceso a agua potable desde hace 18 horas.",
    latitud: 3.4516,
    longitud: -76.532,
    estado: "PRIORIZADA",
    fechaCreacion: "2026-08-20T07:45:00-05:00",
    fechaActualizacion: "2026-08-20T08:00:00-05:00",
    datosEspecificos: {
      categoriaInsumo: "AGUA_POTABLE",
      cantidadRequerida: 400,
    },
  }),
  new Emergency({
    id: "EMG-2024-0004",
    tipo: "STRUCTURAL_DAMAGE_ASSESSMENT",
    prioridad: "BAJA",
    ciudad: "MANIZALES",
    descripcion: "Vivienda de dos pisos presenta agrietamiento visible en muro perimetral tras el sismo.",
    latitud: 5.0689,
    longitud: -75.5174,
    estado: "RECIBIDA",
    fechaCreacion: "2026-08-20T10:15:00-05:00",
    fechaActualizacion: "2026-08-20T10:15:00-05:00",
    datosEspecificos: {
      tipoEdificacion: "Vivienda unifamiliar, 2 niveles",
      nivelAgrietamiento: "MODERADO",
      asentamiento: false,
      riesgoColapsoSobreVias: false,
    },
  }),
  new Emergency({
    id: "EMG-2024-0005",
    tipo: "SEARCH_RESCUE_MEDICAL",
    prioridad: "CRITICA",
    ciudad: "CALI",
    descripcion: "Persona herida bajo escombros tras derrumbe de muro de contención.",
    latitud: 3.4498,
    longitud: -76.5289,
    estado: "VALIDANDO",
    fechaCreacion: "2026-08-20T10:50:00-05:00",
    fechaActualizacion: "2026-08-20T10:52:00-05:00",
    datosEspecificos: {
      personasAtrapadasOHeridas: 1,
      riesgoInminente: true,
      fugaDeGas: false,
      fuego: false,
    },
  }),
  new Emergency({
    id: "EMG-2024-0006",
    tipo: "SHELTER_TEMPORARY_HOUSING",
    prioridad: "ALTA",
    ciudad: "CHOCO",
    descripcion: "Grupo de 12 personas desplazadas por inundación asociada, requiere albergue.",
    latitud: 5.694,
    longitud: -76.661,
    estado: "RESUELTA",
    fechaCreacion: "2026-08-19T22:10:00-05:00",
    fechaActualizacion: "2026-08-20T06:00:00-05:00",
    datosEspecificos: {
      numeroAdultos: 7,
      numeroNinos: 4,
      numeroAdultosMayores: 1,
      estadoHabitabilidadVivienda: "NO_HABITABLE",
    },
  }),
  new Emergency({
    id: "EMG-2024-0007",
    tipo: "BASIC_SUPPLIES_HUMANITARIAN_AID",
    prioridad: "MEDIA",
    ciudad: "MANIZALES",
    descripcion: "Solicitud de kits de primeros auxilios para puesto de atención comunitario.",
    latitud: 5.0703,
    longitud: -75.5138,
    estado: "ASIGNADA",
    fechaCreacion: "2026-08-20T06:30:00-05:00",
    fechaActualizacion: "2026-08-20T07:10:00-05:00",
    datosEspecificos: {
      categoriaInsumo: "KIT_PRIMEROS_AUXILIOS",
      cantidadRequerida: 25,
    },
  }),
  new Emergency({
    id: "EMG-2024-0008",
    tipo: "STRUCTURAL_DAMAGE_ASSESSMENT",
    prioridad: "BAJA",
    ciudad: "PEREIRA",
    descripcion: "Puente peatonal con posible riesgo de colapso, se solicita evaluación técnica.",
    latitud: 4.8115,
    longitud: -75.6903,
    estado: "CANCELADA",
    fechaCreacion: "2026-08-19T19:00:00-05:00",
    fechaActualizacion: "2026-08-19T20:00:00-05:00",
    datosEspecificos: {
      tipoEdificacion: "Puente peatonal",
      nivelAgrietamiento: "LEVE",
      asentamiento: false,
      riesgoColapsoSobreVias: true,
    },
  }),
];
